// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0EYWKeYro9O1XQ2aOX4mdzZOq-wjVT8',
    appId: '1:874735820423:web:1c751c4533a6d0b3666222',
    messagingSenderId: '874735820423',
    projectId: 'my-learning-notes-e0515',
    authDomain: 'my-learning-notes-e0515.firebaseapp.com',
    storageBucket: 'my-learning-notes-e0515.appspot.com',
    measurementId: 'G-K0YKXXDYV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9NU4fbU9bbQiKwCg5dRaajAykrupqh3Y',
    appId: '1:874735820423:android:51ebae916f9a433b666222',
    messagingSenderId: '874735820423',
    projectId: 'my-learning-notes-e0515',
    storageBucket: 'my-learning-notes-e0515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEbxin0xv1OHVnwKhEyJYpwGcPcGyeOU',
    appId: '1:874735820423:ios:6fa4daff9b19152c666222',
    messagingSenderId: '874735820423',
    projectId: 'my-learning-notes-e0515',
    storageBucket: 'my-learning-notes-e0515.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbEbxin0xv1OHVnwKhEyJYpwGcPcGyeOU',
    appId: '1:874735820423:ios:32e92646134bc70b666222',
    messagingSenderId: '874735820423',
    projectId: 'my-learning-notes-e0515',
    storageBucket: 'my-learning-notes-e0515.appspot.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
